config/routes.rb
require 'sidekiq_unique_jobs/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  if Rails.configuration.auth_provider.providable_type == 'DatabaseProvider'
    devise_for :users, controllers: {
      registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', passwords: 'passwords'
    }
  else
    devise_for :users, controllers: {
      registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', passwords: 'passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
    get '/sso-redirect', to: 'application#sso_redirect', as: :sso_redirect
  end

  devise_scope :user do
    get '/sessions/sign_out', to: 'devise/sessions#destroy'
    post '/password/verify', to: 'passwords#verify'
  end

  constraints user_agent: %r{facebookexternalhit/[0-9]|Twitterbot|Pinterest|Google.*snippet} do
    root to: 'social_bot#share', as: :bot_root
  end

  root 'application#index'

  namespace :api, as: nil, defaults: { format: :json } do
    resources :projects, only: %i[index show create update destroy] do
      collection do
        get :last_published
        get :search
      end
      get :markdown, on: :member
    end
    resources :openlab_projects, only: :index
    resources :machines
    resources :machine_categories
    resources :components
    resources :themes
    resources :licences
    resources :statuses
    resources :project_categories
    resources :admins, only: %i[index create destroy]
    resources :settings, only: %i[show update index], param: :name do
      patch '/bulk_update', action: 'bulk_update', on: :collection
      put '/reset/:name', action: 'reset', on: :collection
      get '/is_present/:name', action: 'test_present', on: :collection
    end
    resources :users, only: %i[index create destroy]
    resources :members, only: %i[index show create update destroy] do
      get '/export_subscriptions', action: 'export_subscriptions', on: :collection
      get '/export_reservations', action: 'export_reservations', on: :collection
      get '/export_members', action: 'export_members', on: :collection
      get 'current', action: 'current', on: :collection
      put ':id/merge', action: 'merge', on: :collection
      post 'list', action: 'list', on: :collection
      get 'search/:query', action: 'search', on: :collection
      get 'mapping', action: 'mapping', on: :collection
      patch ':id/complete_tour', action: 'complete_tour', on: :collection
      patch ':id/update_role', action: 'update_role', on: :collection
      patch ':id/validate', action: 'validate', on: :collection
    end
    resources :reservations, only: %i[show index update] do
      post :confirm_payment, on: :collection
    end
    resources :notifications, only: %i[index show update] do
      match :update_all, path: '/', via: %i[put patch], on: :collection
      get 'polling', action: 'polling', on: :collection
      get 'last_unread', action: 'last_unread', on: :collection
    end
    resources :notification_types, only: %i[index]
    resources :notification_preferences, only: %i[index update], param: :notification_type do
      patch '/bulk_update', action: 'bulk_update', on: :collection
    end
    resources :wallet, only: [] do
      get '/by_user/:user_id', action: 'by_user', on: :collection
      get :transactions, on: :member
      put :credit, on: :member
    end

    get '/last_subscribed/:last' => 'members#last_subscribed'

    get 'pricing' => 'pricing#index'
    put 'pricing' => 'pricing#update'

    resources :prices, only: %i[create index update destroy] do
      post 'compute', on: :collection
    end
    resources :prepaid_packs
    resources :coupons do
      post 'validate', action: 'validate', on: :collection
      post 'send', action: 'send_to', on: :collection
    end
    resources :user_packs, only: %i[index]

    resources :trainings_pricings, only: %i[index update]

    resources :availabilities do
      get 'machines/:machine_id', action: 'machine', on: :collection
      get 'trainings/:training_id', action: 'trainings', on: :collection
      get 'spaces/:space_id', action: 'spaces', on: :collection
      get 'reservations', on: :member
      get 'public', on: :collection
      get '/export_index', action: 'export_availabilities', on: :collection
      put ':id/lock', action: 'lock', on: :collection
    end

    resources :groups, only: %i[index create update destroy]
    resources :subscriptions, only: %i[show] do
      get 'payment_details', action: 'payment_details', on: :member
      patch 'cancel', on: :member
    end
    resources :plan_categories
    resources :plans do
      get 'durations', on: :collection
    end
    resources :slots_reservations, only: [:update] do
      put 'cancel', on: :member
      put 'validate', on: :member
      put 'invalidate', on: :member
    end

    resources :events do
      get 'upcoming/:limit', action: 'upcoming', on: :collection
    end

    resources :invoices, only: %i[index show create] do
      get 'download', action: 'download', on: :member
      post 'list', action: 'list', on: :collection
      get 'first', action: 'first', on: :collection
    end

    resources :payment_schedules, only: %i[index show update] do
      post 'list', action: 'list', on: :collection
      put 'cancel', on: :member
      get 'download', on: :member
      get 'items/:id', action: 'show_item', on: :collection
      post 'items/:id/cash_check', action: 'cash_check', on: :collection
      post 'items/:id/confirm_transfer', action: 'confirm_transfer', on: :collection
      post 'items/:id/refresh_item', action: 'refresh_item', on: :collection
      post 'items/:id/pay_item', action: 'pay_item', on: :collection
    end

    resources :i_calendar, only: %i[index create destroy] do
      get 'events', on: :member
      post 'sync', on: :member
    end

    resources :supporting_document_types
    resources :supporting_document_files, only: %i[index show create update] do
      get 'download', on: :member
    end
    resources :supporting_document_refusals, only: %i[index show create]

    resources :profile_custom_fields

    resources :product_categories do
      patch 'position', on: :member
    end

    resources :products do
      put 'clone', on: :member
      get 'stock_movements', on: :member
    end
    resources :cart, only: %i[create] do
      put 'add_item', on: :collection
      put 'remove_item', on: :collection
      put 'set_quantity', on: :collection
      put 'set_offer', on: :collection
      put 'refresh_item', on: :collection
      post 'validate', on: :collection
      post 'create_item', on: :collection
      put 'set_customer', on: :collection
    end
    resources :checkout, only: %i[] do
      post 'payment', on: :collection
      post 'confirm_payment', on: :collection
    end
    resources :orders, except: %i[create] do
      get 'withdrawal_instructions', on: :member
    end

    resources :children do
      patch ':id/validate', action: 'validate', on: :collection
    end

    resources :trainings do
      get :availabilities, on: :member
    end
    resources :credits do
      get 'user/:id/:resource', action: :user_resource, on: :collection
    end
    resources :categories
    resources :event_themes
    resources :age_ranges
    resources :statistics, only: [:index]
    resources :custom_assets, only: %i[show create update]
    resources :tags
    resources :stylesheets, only: [:show]
    resources :auth_providers do
      get 'mapping_fields', on: :collection
      get 'active', action: 'active', on: :collection
      post 'send_code', action: 'send_code', on: :collection
      get 'strategy_name', action: 'strategy_name', on: :collection
    end
    resources :abuses, only: %i[index create destroy]
    resources :open_api_clients, only: %i[index create update destroy] do
      patch :reset_token, on: :member
    end
    resources :price_categories
    resources :spaces
    resources :accounting_periods do
      get 'last_closing_end', on: :collection
      get 'archive', action: 'download_archive', on: :member
    end
    post 'accounting/export' => 'accounting_exports#export'
    resources :reservation_contexts do
      get :applicable_on_values, on: :collection
    end

    get 'translations/:locale/:state' => 'translations#show', :constraints => { state: %r{[^/]+} }

    get 'exports/:id/download' => 'exports#download'
    post 'exports/status' => 'exports#status'

    resources :imports, only: [:show] do
      post 'members', action: 'members', on: :collection
    end

    post 'version' => 'version#show'

    post 'stripe/confirm_payment' => 'stripe/confirm_payment'
    get 'stripe/online_payment_status' => 'stripe/online_payment_status'
    get 'stripe/setup_intent/:user_id' => 'stripe#setup_intent'
    post 'stripe/setup_subscription' => 'stripe/setup_subscription'
    post 'stripe/confirm_subscription' => 'stripe#confirm_subscription'
    post 'stripe/update_card' => 'stripe#update_card'

    post 'payzen/sdk_test' => 'payzen#sdk_test'
    post 'payzen/create_payment' => 'payzen#create_payment'
    post 'payzen/confirm_payment' => 'payzen#confirm_payment'
    post 'payzen/confirm_payment_schedule' => 'payzen#confirm_payment_schedule'
    post 'payzen/check_hash' => 'payzen#check_hash'
    post 'payzen/create_token' => 'payzen#create_token'
    post 'payzen/update_token' => 'payzen#update_token'
    post 'payzen/check_cart' => 'payzen#check_cart'

    post 'local_payment/confirm_payment' => 'local_payment#confirm_payment'

    get 'analytics/data' => 'analytics#data'

    post 'files/mime_type' => 'files#mime'
  end

  namespace :rss, as: nil, defaults: { format: :xml } do
    resources :projects, only: [:index], as: 'rss_projects'
    resources :events, only: [:index], as: 'rss_events'
  end

  namespace :open_api do
    namespace :v1 do
      scope only: :index do
        resources :plans, only: %i[index show]
        resources :plan_categories

app/controllers/application_controller.rb
# frozen_string_literal: true

# Main controller for the backend application. All controllers inherits from it
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_action :set_csrf_cookie

  respond_to :html, :json

  before_action :configure_permitted_parameters, if: :devise_controller?
  around_action :switch_locale

  # Globally rescue Authorization Errors in controller.
  # Returning 403 Forbidden if permission is denied
  rescue_from Pundit::NotAuthorizedError, with: :permission_denied

  def index; end

  def sso_redirect
    @authorization_token = request.query_parameters[:auth_token]
    @authentication_token = form_authenticity_token
    @active_provider = AuthProvider.active
  end

  protected

  def set_csrf_cookie
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [
                                        {
                                          profile_attributes: %i[phone last_name first_name interest software_mastered],
                                          invoicing_profile_attributes: [
                                            organization_attributes: [:name, { address_attributes: [:address] }],
                                            user_profile_custom_fields_attributes: %i[profile_custom_field_id value],
                                            address_attributes: [:address]
                                          ],
                                          statistic_profile_attributes: %i[gender birthday]
                                        },
                                        :username, :is_allow_contact, :is_allow_newsletter, :cgu, :group_id
                                      ])
  end

  def default_url_options
    {
      host: Rails.application.secrets.default_host,
      protocol: Rails.application.secrets.default_protocol
    }
  end

  def permission_denied
    head :forbidden
  end

  # Set the configured locale for each action (API call)
  # @see https://guides.rubyonrails.org/i18n.html
  def switch_locale(&)
    locale = params[:locale] || Rails.application.secrets.rails_locale
    I18n.with_locale(locale, &)
  end

  # @return [User]
  # This is a placeholder for Devise's current_user.
  # As Devise generate the method at runtime, IDEs autocomplete features will complain about 'method not found'
  def current_user
    super
  end

  # This is a placeholder for Devise's authenticate_user! method.
  def authenticate_user!
    super
  end

  # N+1 query detection (https://github.com/flyerhzm/bullet)
  def skip_bullet
    previous_value = Bullet.enable?
    Bullet.enable = false
    yield
  ensure
    Bullet.enable = previous_value
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Various helpers methods
module ApplicationHelper
  require 'message_format'

  ##
  # Verify if the provided attribute is in the provided attributes array, whatever it exists or not
  # @param attributes {Array|nil}
  # @param attribute {String}
  ##
  def attribute_requested?(attributes, attribute)
    attributes.try(:include?, attribute)
  end

  def bootstrap_class_for(flash_type)
    { flash: 'alert-success', alert: 'alert-danger', notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "flash-message alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end

  def print_slot(starting, ending)
    "#{starting.strftime('%H:%M')} - #{ending.strftime('%H:%M')}"
  end

  def class_exists?(class_name)
    klass = Module.const_get(class_name)
    klass.is_a?(Class)
  rescue NameError
    false
  end

  ##
  # Allow to treat a rails i18n key as a MessageFormat interpolated pattern. Used in ruby views (API/mails)
  # @param key {String} Ruby-on-Rails I18n key (from config/locales/xx.yml)
  # @param interpolations {Hash} list of variables to interpolate, following ICU MessageFormat syntax
  ##
  def _t(key, interpolations)
    message = MessageFormat.new(I18n.t(scope_key_by_partial(key)), I18n.locale.to_s)
    text = message.format(interpolations)
    if html_safe_translation_key?(key)
      text.html_safe # rubocop:disable Rails/OutputSafety
    else
      text
    end
  end

  def bool_to_sym(bool)
    bool ? :true : :false # rubocop:disable Lint/BooleanSymbol
  end

  def str_to_bool(str, default = 'true')
    str.to_s.casecmp(default).zero?
  end

  def amount_to_f(amount)
    amount / 100.00
  end

  # Return the given amount in centimes, without floating-point imprecision errors
  def to_centimes(amount)
    (BigDecimal(amount.to_s) * 100.0).to_f
  end

  # Return the given parameter as it, or as an array if it can be parsed as an array
  def may_array(param)
    return param if param.is_a?(Array)

    return param unless param.chars&.first == '[' && param.chars&.last == ']'

    param.gsub(/[\[\]]/i, '').split(',')
  end

  private

  ## inspired by gems/actionview-4.2.5/lib/action_view/helpers/translation_helper.rb
  # rubocop:disable Rails/HelperInstanceVariable
  def scope_key_by_partial(key)
    if key.to_s.first == '.'
      raise "Cannot use t(#{key.inspect}) shortcut because path is not available" unless @virtual_path # rubocop:disable Rails/HelperInstanceVariable

      @virtual_path.gsub(%r{/_?}, '.') + key.to_s # rubocop:disable Rails/HelperInstanceVariable
    else
      key
    end
  end
  # rubocop:enable Rails/HelperInstanceVariable

  def html_safe_translation_key?(key)
    key.to_s =~ /(\b|_|\.)html$/
  end
end

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" ng-app="application" class="app" ng-strict-di>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%=Setting.get('fablab_name')%></title>

  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,800,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Loved+by+the+King' rel='stylesheet' type='text/css'>
  <% if Rails.env.staging? && Rails.application.secrets.enable_in_context_translation %>
    <script type="text/javascript">
      var _jipt = [];
      _jipt.push(['project', 'fab-manager']);
    </script>
    <script type="text/javascript" src="//cdn.crowdin.com/jipt/jipt.js"></script>
  <% end %>

  <% if Setting.get('payzen_endpoint') %>
    <% endpoint = Setting.get('payzen_endpoint') %>
    <%=stylesheet_link_tag "#{endpoint}/static/js/krypton-client/V4.0/ext/classic-reset.css" %>
    <%=javascript_include_tag "#{endpoint}/static/js/krypton-client/V4.0/ext/classic.js" %>
    <% if Rails.env.development? %>
      <%=javascript_include_tag "#{endpoint}/static/js/krypton-client/V4.0/ext/classic.js.map" %>
    <% end %>
  <% end %>

  <script type="text/javascript">
      var Fablab = Fablab || {};

      Fablab.machinesModule = ('<%= Setting.get('machines_module') %>' === 'true');
      Fablab.plansModule = ('<%= Setting.get('plans_module') %>' === 'true');
      Fablab.spacesModule = ('<%= Setting.get('spaces_module') %>' === 'true');
      Fablab.trainingsModule = ('<%= Setting.get('trainings_module') %>' === 'true');
      Fablab.storeModule = ('<%= Setting.get('store_module') %>' === 'true');
      Fablab.walletModule = ('<%= Setting.get('wallet_module') %>' === 'true');
      Fablab.publicAgendaModule = ('<%= Setting.get('public_agenda_module') %>' === 'true');
      Fablab.statisticsModule = ('<%= Setting.get('statistics_module') %>' === 'true');
      Fablab.defaultHost = "<%= Rails.application.secrets.default_host %>";
      Fablab.trackingId = "<%= Setting.get('tracking_id') %>";
      Fablab.adminSysId = parseInt("<%= User.adminsys&.id %>", 10);
      Fablab.activeProviderType = "<%= AuthProvider.active&.providable_type %>";
      Fablab.storeHidden = ('<%= Setting.get('store_hidden') %>' === 'true');

      // i18n stuff
      Fablab.locale = "<%= Rails.application.secrets.app_locale %>";
      Fablab.moment_locale = "<%= Rails.application.secrets.moment_locale %>";
      Fablab.summernote_locale = "<%= Rails.application.secrets.summernote_locale %>";
      Fablab.fullcalendar_locale = "<%= Rails.application.secrets.fullcalendar_locale %>";
      Fablab.intl_locale = "<%= Rails.application.secrets.intl_locale %>";
      Fablab.intl_currency = "<%= Rails.application.secrets.intl_currency %>";
      Fablab.timezone = "<%= Time.zone.tzinfo.name %>";
      Fablab.timezone_offset = "<%= Time.zone.formatted_offset %>";
      Fablab.translations = {
        app: {
          shared: {
            buttons: <%= I18n.t('app.shared.buttons').to_json.html_safe %>,
            messages: <%= I18n.t('app.shared.messages').to_json.html_safe %>
          }
        }
      };
      Fablab.weekStartingDay = <%= Date.parse(Rails.application.secrets.week_starting_day).strftime('%w') %>;
      Fablab.d3DateFormat = "<%= Rails.application.secrets.d3_date_format %>";
      Fablab.uibDateFormat = "<%= Rails.application.secrets.uib_date_format %>";
      Fablab.maxSupportingDocumentFileSize = <%= ENV.fetch('MAX_SUPPORTING_DOCUMENT_FILE_SIZE' ,5.megabytes.to_i) %>;

      // feature tour (used when feature_tour_display = session)
      Fablab.sessionTours = [];
  </script>

  <%= stylesheet_pack_tag 'application', 'plugins', 'printer' %>
  <% unless Stylesheet.theme.nil? %>
  <link rel="stylesheet" media="all" href="<%= stylesheet_path(Stylesheet.theme.id) %>-<%= Stylesheet.theme.updated_at.to_i.to_s %>.css" />
  <%  end %>
  <% unless Stylesheet.home_page.nil? %>
    <link rel="stylesheet" media="all" href="<%= stylesheet_path(Stylesheet.home_page.id) %>-<%= Stylesheet.home_page.updated_at.to_i.to_s %>.css" />
  <%  end %>
  <base href="/"></base>

  <% if CustomAsset.get_url('favicon-file') %>
    <link rel="shortcut icon" type="image/x-icon" href="<%= CustomAsset.get_url('favicon-file') %>">
    <link rel="shortcut icon" type="image/ico" href="<%= CustomAsset.get_url('favicon-file') %>">
  <% end %>

  <!-- RSS -->
  <link rel="alternate" type="application/rss+xml" title="RSS: <%= t('app.public.projects_list.the_fablab_projects') %>" href="<%= rss_projects_path %>.xml">
  <link rel="alternate" type="application/rss+xml" title="RSS: <%= t('app.public.events_list.the_fablab_s_events') %>" href="<%= rss_events_path %>.xml">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body ng-controller="ApplicationController"
      ng-init="setCurrentUser(<%= current_user ? current_user.to_json : 'null' %>)"
      ng-cloak>
  <div growl></div>

  <%= flash_messages %>

  <section class="vbox">

    <header id="top-header" class="header header-md navbar navbar-fixed-top-xs">
      <div ui-view="header"></div>
    </header>

    <section ui-view="content">
      <section class="hbox stretch">
        <aside id="nav" class="aside-md bg-red hidden-print" ui-view="leftnav"></aside>

        <section id="content">
          <section class="vbox">
            <section id="cookies-modal" ui-view="cookies">
            </section>
            <section id="content-main" class="scrollable" ui-view="main">
            </section>
          </section>
        </section>

      </section> <!-- /.hbox -->
    </section>

  </section> <!-- /.vbox -->

  <div class="app-generator">
    <span class="app-version" uib-tooltip="{{'app.public.common.version' | translate}} {{version.current}}" ng-if="currentUser && currentUser.role == 'admin'" ng-click="versionModal()">
      <i class="fa fa-question-circle" aria-label="Version ?" ng-show="version.up_to_date"></i>
      <i class="fa fa-refresh text-info pointer" aria-label="Upgrade required" ng-show="!version.up_to_date && !version.security"></i>
      <i class="fa fa-warning text-danger pointer" aria-label="Security upgrade required" ng-show="!version.up_to_date && version.security"></i>
    </span>
    <span class="text-sm">Powered by <a href="http://www.fab-manager.com" target="_blank">Fab-manager</a></span>
  </div>

<%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/application/sso_redirect.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="robots" content="noindex, follow">
  <title>Redirect to SSO</title>
</head>
<body>
  <% param = @authorization_token ? "?auth_token=#{@authorization_token}" : '' %>
  <% url_path = URI.join("#{ENV.fetch('DEFAULT_PROTOCOL')}://#{ENV.fetch('DEFAULT_HOST')}", "users/auth/#{@active_provider.strategy_name}#{param}") %>
  <form id="redirect-form" action="<%=url_path%>" method="post" target="_self">
    <%= hidden_field_tag :authenticity_token, @authentication_token %>
    <noscript>
      <input type="submit" value="⇒ Click here to continue"/>
    </noscript>
  </form>
  <script type="text/javascript">
    document.forms['redirect-form'].submit();
  </script>
</body>