config/routes.rb
require 'sidekiq_unique_jobs/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  if Rails.configuration.auth_provider.providable_type == 'DatabaseProvider'
    devise_for :users, controllers: {
      registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', passwords: 'passwords'
    }
  else
    devise_for :users, controllers: {
      registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations', passwords: 'passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }
    get '/sso-redirect', to: 'application#sso_redirect', as: :sso_redirect
  end

  devise_scope :user do
    get '/sessions/sign_out', to: 'devise/sessions#destroy'
    post '/password/verify', to: 'passwords#verify'
  end

  constraints user_agent: %r{facebookexternalhit/[0-9]|Twitterbot|Pinterest|Google.*snippet} do
    root to: 'social_bot#share', as: :bot_root
  end

  root 'application#index'

  namespace :api, as: nil, defaults: { format: :json } do
    resources :projects, only: %i[index show create update destroy] do
      collection do
        get :last_published
        get :search
      end
      get :markdown, on: :member
    end
    resources :openlab_projects, only: :index
    resources :machines
    resources :machine_categories
    resources :components
    resources :themes
    resources :licences
    resources :statuses
    resources :project_categories
    resources :admins, only: %i[index create destroy]
    resources :settings, only: %i[show update index], param: :name do
      patch '/bulk_update', action: 'bulk_update', on: :collection
      put '/reset/:name', action: 'reset', on: :collection
      get '/is_present/:name', action: 'test_present', on: :collection
    end
    resources :users, only: %i[index create destroy]
    resources :members, only: %i[index show create update destroy] do
      get '/export_subscriptions', action: 'export_subscriptions', on: :collection
      get '/export_reservations', action: 'export_reservations', on: :collection
      get '/export_members', action: 'export_members', on: :collection
      get 'current', action: 'current', on: :collection
      put ':id/merge', action: 'merge', on: :collection
      post 'list', action: 'list', on: :collection
      get 'search/:query', action: 'search', on: :collection
      get 'mapping', action: 'mapping', on: :collection
      patch ':id/complete_tour', action: 'complete_tour', on: :collection
      patch ':id/update_role', action: 'update_role', on: :collection
      patch ':id/validate', action: 'validate', on: :collection
    end
    resources :reservations, only: %i[show index update] do
      post :confirm_payment, on: :collection
    end
    resources :notifications, only: %i[index show update] do
      match :update_all, path: '/', via: %i[put patch], on: :collection
      get 'polling', action: 'polling', on: :collection
      get 'last_unread', action: 'last_unread', on: :collection
    end
    resources :notification_types, only: %i[index]
    resources :notification_preferences, only: %i[index update], param: :notification_type do
      patch '/bulk_update', action: 'bulk_update', on: :collection
    end
    resources :wallet, only: [] do
      get '/by_user/:user_id', action: 'by_user', on: :collection
      get :transactions, on: :member
      put :credit, on: :member
    end

    get '/last_subscribed/:last' => 'members#last_subscribed'

    get 'pricing' => 'pricing#index'
    put 'pricing' => 'pricing#update'

    resources :prices, only: %i[create index update destroy] do
      post 'compute', on: :collection
    end
    resources :prepaid_packs
    resources :coupons do
      post 'validate', action: 'validate', on: :collection
      post 'send', action: 'send_to', on: :collection
    end
    resources :user_packs, only: %i[index]

    resources :trainings_pricings, only: %i[index update]

    resources :availabilities do
      get 'machines/:machine_id', action: 'machine', on: :collection
      get 'trainings/:training_id', action: 'trainings', on: :collection
      get 'spaces/:space_id', action: 'spaces', on: :collection
      get 'reservations', on: :member
      get 'public', on: :collection
      get '/export_index', action: 'export_availabilities', on: :collection
      put ':id/lock', action: 'lock', on: :collection
    end

    resources :groups, only: %i[index create update destroy]
    resources :subscriptions, only: %i[show] do
      get 'payment_details', action: 'payment_details', on: :member
      patch 'cancel', on: :member
    end
    resources :plan_categories
    resources :plans do
      get 'durations', on: :collection
    end
    resources :slots_reservations, only: [:update] do
      put 'cancel', on: :member
      put 'validate', on: :member
      put 'invalidate', on: :member
    end

    resources :events do
      get 'upcoming/:limit', action: 'upcoming', on: :collection
    end

    resources :invoices, only: %i[index show create] do
      get 'download', action: 'download', on: :member
      post 'list', action: 'list', on: :collection
      get 'first', action: 'first', on: :collection
    end

    resources :payment_schedules, only: %i[index show update] do
      post 'list', action: 'list', on: :collection
      put 'cancel', on: :member
      get 'download', on: :member
      get 'items/:id', action: 'show_item', on: :collection
      post 'items/:id/cash_check', action: 'cash_check', on: :collection
      post 'items/:id/confirm_transfer', action: 'confirm_transfer', on: :collection
      post 'items/:id/refresh_item', action: 'refresh_item', on: :collection
      post 'items/:id/pay_item', action: 'pay_item', on: :collection
    end

    resources :i_calendar, only: %i[index create destroy] do
      get 'events', on: :member
      post 'sync', on: :member
    end

    resources :supporting_document_types
    resources :supporting_document_files, only: %i[index show create update] do
      get 'download', on: :member
    end
    resources :supporting_document_refusals, only: %i[index show create]

    resources :profile_custom_fields

    resources :product_categories do
      patch 'position', on: :member
    end

    resources :products do
      put 'clone', on: :member
      get 'stock_movements', on: :member
    end
    resources :cart, only: %i[create] do
      put 'add_item', on: :collection
      put 'remove_item', on: :collection
      put 'set_quantity', on: :collection
      put 'set_offer', on: :collection
      put 'refresh_item', on: :collection
      post 'validate', on: :collection
      post 'create_item', on: :collection
      put 'set_customer', on: :collection
    end
    resources :checkout, only: %i[] do
      post 'payment', on: :collection
      post 'confirm_payment', on: :collection
    end
    resources :orders, except: %i[create] do
      get 'withdrawal_instructions', on: :member
    end

    resources :children do
      patch ':id/validate', action: 'validate', on: :collection
    end

    resources :trainings do
      get :availabilities, on: :member
    end
    resources :credits do
      get 'user/:id/:resource', action: :user_resource, on: :collection
    end
    resources :categories
    resources :event_themes
    resources :age_ranges
    resources :statistics, only: [:index]
    resources :custom_assets, only: %i[show create update]
    resources :tags
    resources :stylesheets, only: [:show]
    resources :auth_providers do
      get 'mapping_fields', on: :collection
      get 'active', action: 'active', on: :collection
      post 'send_code', action: 'send_code', on: :collection
      get 'strategy_name', action: 'strategy_name', on: :collection
    end
    resources :abuses, only: %i[index create destroy]
    resources :open_api_clients, only: %i[index create update destroy] do
      patch :reset_token, on: :member
    end
    resources :price_categories
    resources :spaces
    resources :accounting_periods do
      get 'last_closing_end', on: :collection
      get 'archive', action: 'download_archive', on: :member
    end
    post 'accounting/export' => 'accounting_exports#export'
    resources :reservation_contexts do
      get :applicable_on_values, on: :collection
    end

    get 'translations/:locale/:state' => 'translations#show', :constraints => { state: %r{[^/]+} }

    get 'exports/:id/download' => 'exports#download'
    post 'exports/status' => 'exports#status'

    resources :imports, only: [:show] do
      post 'members', action: 'members', on: :collection
    end

    post 'version' => 'version#show'

    post 'stripe/confirm_payment' => 'stripe/confirm_payment'
    get 'stripe/online_payment_status' => 'stripe/online_payment_status'
    get 'stripe/setup_intent/:user_id' => 'stripe#setup_intent'
    post 'stripe/setup_subscription' => 'stripe/setup_subscription'
    post 'stripe/confirm_subscription' => 'stripe#confirm_subscription'
    post 'stripe/update_card' => 'stripe#update_card'

    post 'payzen/sdk_test' => 'payzen#sdk_test'
    post 'payzen/create_payment' => 'payzen#create_payment'
    post 'payzen/confirm_payment' => 'payzen#confirm_payment'
    post 'payzen/confirm_payment_schedule' => 'payzen#confirm_payment_schedule'
    post 'payzen/check_hash' => 'payzen#check_hash'
    post 'payzen/create_token' => 'payzen#create_token'
    post 'payzen/update_token' => 'payzen#update_token'
    post 'payzen/check_cart' => 'payzen#check_cart'

    post 'local_payment/confirm_payment' => 'local_payment#confirm_payment'

    get 'analytics/data' => 'analytics#data'

    post 'files/mime_type' => 'files#mime'
  end

  namespace :rss, as: nil, defaults: { format: :xml } do
    resources :projects, only: [:index], as: 'rss_projects'
    resources :events, only: [:index], as: 'rss_events'
  end

  namespace :open_api do
    namespace :v1 do
      scope only: :index do
        resources :plans, only: %i[index show]
        resources :plan_categories

app/views/layouts/notifications_mailer.html.erb
<% fablab_name = Setting.get('fablab_name') %>
<% fablab_gender = Setting.get('name_genre') %>
<% primary_color = Stylesheet.primary %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link href="http://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet" type="text/css">
  <style type="text/css">
    /* Client-specific Styles */
    #outlook a{padding:0;} /* Force Outlook to provide a "view in browser" button. */
    a{color:<%=primary_color%>;} a:hover{color:<%=primary_color%>;}
    </style>
</head>
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="width:100% !important; -webkit-text-size-adjust:none; margin:0; padding:0; background-color:#fafafa; font-family:Arial; font-size:14px;">
  <center>
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="backgroundTable" style="height:100% !important; margin:0; padding:0; width:100% !important; background-color:#fafafa;">
      <tr>
        <td align="center" valign="top">
          <p style="font-size:9px;">&nbsp;</p>
          <table border="0" cellpadding="20" cellspacing="0" width="600" id="templateContainer" style="width:600px; border:1px solid #dddddd; background-color:#fff; -webkit-border-radius:2px; -moz-border-radius:2px; -ms-border-radius:2px; -o-border-radius:2px; border-radius:2px;">
            <tr>
              <td align="center">
                <% if CustomAsset.get_url('logo-file') %>
                  <a href="<%= root_url %>">
                    <img src="<%= File.join(root_url, CustomAsset.get_url('logo-file')) %>"
                         alt="<%=fablab_name%>"
                         width="140" />
                  </a>
                <% else %>
                  <a href="<%= root_url %>">
                    <img src="<%= File.join(root_url, asset_pack_path('static/fabmanager-logo.png')) %>"
                         alt="<%=fablab_name%>"
                         width="140" />
                  </a>
                <% end %>
              </td>
            </tr>
            <tr>
              <td id="title" style="font-size:14px; color:#fff; font-weight:bold; background-color:<%=primary_color%>"><%= message.subject %></td>
            </tr>
            <tr>
              <td>
                <%= yield %>
              </td>
            </tr>
            <tr>
              <td>
                <p>
                  <%= _t(".see_you_later", { GENDER:fablab_gender })
                      # messageFormat
                  %> <a href="<%= root_url %>" style="color:<%=primary_color%>"> <%=fablab_name%></a>.</p>
                <p><%= t(".sincerely") %><br><%= t(".signature") %></p>
              </td>
            </tr>
            <tr>
              <td id="contactTd" style="color:#666; font-size:11px; background-color:#f3f3f3; padding:13px 20px 13px 20px; border-top:2px dashed #ddd;"><%= t('.do_not_reply') %></td>
            </tr>
          </table>
          <p style="font-size:9px;">&nbsp;</p>
        </td>
      </tr>
    </table>
  </center>
</body>
</html>